Site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from about.views import show_about
from contacts.views import show_contacts
from delivery.views import show_delivery
from payment.views import show_payment
from main.views import show_main


urlpatterns = [
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^payment/', show_payment, name='ShowPayment'),
    url(r'^delivery/', show_delivery, name='ShowDelivery'),
    url(r'^contacts/', show_contacts, name='ShowContacts'),
    url(r'^about/', show_about, name='ShowAbout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', show_main, name='MainPage'),
    url(r'^search/', include('haystack.urls', namespace='show_search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='CartAdd'),
    url(r'^$', views.cart_detail, name='CartDetail'),
]

catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.category_list, name='MainCatalog'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.category_list, name='CategoryList'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$', views.product_page, name='ProductPage'),
    url(r'^search$', views.search_view, name='SearchView'),
]

cupons/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply', views.cupon_apply, name='apply')
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='AdminOrderPDF')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Products
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApllyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    cupon_apply_form = CuponApllyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends "catalog/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
    <div class="product-list col-sm-9">
      <h1> Ваша корзина товаров </h1>
      <table class="cart-table">
        <thead>
          <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Полная цена</th>
            <th>Цена</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="cart-img">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td><form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
        {{ item.update_quantity_form.quantity }}
        {{ item.update_quantity_form.update }}
        {% csrf_token %}
        <input type="submit" value="Обновить">
        </form></td>
                <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
                <td class="num">{{ item.price }} руб.</td>
                <td class="num">{{ item.total_price }} руб.</td>
              </tr>
            {% endwith %}
          {% endfor %}

          {% if cart.cupon %}
              <tr class="subtotal">
                <td>Сумма без скидки</td>
                <td colspan="4"></td>
                <td>{{ cart.get_total_price }}</td>
              </tr>
              <tr>
                <td>
                  "{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % ниже)
                </td>
                <td colspan="4"></td>
                <td class="num discount">- {{ cart.get_discount|floatformat:"2" }} руб.</td>
              </tr>
            {% endif %}

            <tr class="total">
                <td colspan="4"></td>
                <td> Всего: </td>
                <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} руб.</td>
            </tr>
        </tbody>
    </table>

        <p>Применить купон:</p>
      <form action="{% url "cupon:apply" %}" method="post" class="add">
        {% csrf_token %}
        {{ cupon_apply_form }}
        <input type="submit" value="Обновить">
      </form>
        <p class="text-right">
        <a href="{% url "catalog:MainCatalog"%}" class="btn">Вернуться к покупкам</a>
        <a href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
      </p>
    </div>
{% endblock %}