Site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from about.views import show_about
from contacts.views import show_contacts
from delivery.views import show_delivery
from payment.views import show_payment
from main.views import show_main


urlpatterns = [
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^payment/', show_payment, name='ShowPayment'),
    url(r'^delivery/', show_delivery, name='ShowDelivery'),
    url(r'^contacts/', show_contacts, name='ShowContacts'),
    url(r'^about/', show_about, name='ShowAbout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', show_main, name='MainPage'),
    url(r'^search/', include('haystack.urls', namespace='show_search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='CartAdd'),
    url(r'^$', views.cart_detail, name='CartDetail'),
]

catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.category_list, name='MainCatalog'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.category_list, name='CategoryList'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$', views.product_page, name='ProductPage'),
    url(r'^search$', views.search_view, name='SearchView'),
]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Catalog(models.Model):
    class Meta():
        db_table = 'category'
        verbose_name_plural = "Категории"
        verbose_name = "Категория"

    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name="Категория")
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children',db_index=True, verbose_name = u'Родительский класс')
    slug = models.SlugField(max_length=200, unique=True, db_index=True, db_column='slug')
    image = models.ImageField(blank=True, verbose_name="Изображение категории")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:CategoryList', args=[self.slug])


class Products(models.Model):
    db_table = 'products_id'
    name = models.CharField(max_length=100,unique=True,verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    description = models.TextField(blank=True, verbose_name='Описание')
    vendor_code = models.CharField(max_length=6, unique=True, verbose_name='Артикул')
    category = models.ForeignKey(Catalog, verbose_name='Раздел',related_name='+')
    slug = models.SlugField(max_length=200, unique=True, db_index=True)
    available = models.BooleanField(default=False, verbose_name="В наличии")
    image = models.ImageField(blank=True, verbose_name="Изображение товара")

    class Meta():
        db_table = 'products' # меняет название таблицы в БД
        verbose_name_plural = "Товары"
        verbose_name = "Товар"
        ordering = ['name']
        index_together = [['id', 'slug']]

    def get_absolute_url(self):
        cur_obj = self.category_id
        out_obj = Catalog.objects.all()
        for x in out_obj:
            if x.id == cur_obj:
                category_slug = x.slug
        return reverse('catalog:ProductPage', args=[category_slug, self.slug])

    def __str__(self):
        return (self.name)

catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm


def category_list(request, category_slug=None):
    category = None
    categories = Catalog.objects.all()
    products = Products.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Catalog, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'catalog/category.html', {
            'category': category,
            'categories': categories,
            'products': products,
            'category_slug': category_slug,
    })


def product_page(request, category_slug, slug):
    products = Products.objects.all()
    category = get_object_or_404(Catalog, slug=category_slug)
    categories = Catalog.objects.all()
    product = get_object_or_404(Products,  slug=slug)
    products = products.filter(category=category)
    cart_product_form = CartAddProductForm()
    return render(request, 'catalog/products.html', {
            'product': product,
            'category': category,
            'products': products,
            'cart_product_form': cart_product_form,
            'categories': categories,
          })


def search_view (request):
    products = Products.objects.all()
    product = get_object_or_404(Products)
    return render(request, 'catalog/base.html', {
        'product': product,
        'products': products,
    })

templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
<title>{% block title %}{% endblock %}</title>
</head>
  <body>
        <section id="header">
            <div class="top">
              <td><a href="{% url "MainPage" %}">Мой онлайн-магазин</a></td>
            </div>
            <div class="e-cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Ваша корзина:
                        <a href="{% url "cart:CartDetail" %}">
                            {{ total_items }} тов. {{ cart.get_total_price }} руб.
                        </a>
                    {% else %}
                        <div class="top-bl">
                            Ваша корзина пуста
                            </div>
                        </div>
                    {% endif %}
                 {% endwith %}
            </div>
        </section>
        <section id="content row" class="container">
        <div class="info-line">
            <img src="{% static "logo.jpg"%}" class="logo-img">
            <div class="info-text">
                <a href="{% url "ShowAbout" %}">О_компании</a>
                <a href="{% url "ShowDelivery" %}">Доставка</a>
                <a href="{% url "ShowPayment" %}">Оплата</a>
                <a href="{% url "ShowContacts" %}">Контакты</a>
                <a href="{% url "show_search:haystack_search" %}">Поиск</a>
            </div>
        </div>

        <div class="breadcrumbs">
        <! крошки для главной >
            {% if main %}
            {% else %} <a href="{% url "MainPage" %}">Главная</a>
            {% endif %}

        <! крошки для инфо-разделов >
            {% if app_url %}
                {% for inf in info %}
                    <a href="{{ inf.app_url }}">/{{ inf.title }}</a>
                {% endfor %}
                {% elif main %}
                {% elif form %}
                <a href="{% url "show_search:haystack_search" %}">/Поиск</a>
                <! крошки для каталога >
                {% else %}<a href="{% url "catalog:MainCatalog" %}">/Каталог/</a>
            {% endif %}

        <! крошки для категорий >
            {% for cat in categories %}
                {% if category.slug == cat.slug %}
                     <a href="{{ cat.get_absolute_url }}">{{ cat.name }}/</a>
                {% endif %}
            {% endfor %}

        <! крошки для товара >
            {% for prod in products %}
                {% if prod.slug == product.slug %}
                    <a href="{{ prod.get_absolute_url }}">{{ prod.name }}</a>
                {% endif %}
            {% endfor %}
        </div>

            {% block content %}{% endblock %}
        </section>
  </body>
</html>

templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block title %}
    {% if category %} {{ category.name }} {% else %} Каталог {% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar" class="col-sm-3">
        <h2>Категории</h2>
        <ul>
            {% for cat in categories %}
                    <li {% if category.slug == cat.slug %} class='selected' {% endif %}>
                         <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                    </li>
            {% endfor %}
        </ul>
    </div>
  <div id="main" class="product-list col-sm-9">
    <h2>{% if category %}{{ category.name }}{% else %} Каталог товаров {% endif %}</h2>
        <div class="items row">
            {% if category %}
                {% for product in products %}
                  <div class="item col-sm-4">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "no-image.jpg"%}{% endif %}" class="img-responsive">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    <div class="category-price"> Цена: {{ product.price }} руб. </div>
                  </div>
                {% endfor %}
                {% else %}
                {% for cat in categories %}
                <div class="item col-sm-4">
                    <img src="{% if cat.image %}{{ cat.image.url }}{% else %}{% static "no-image.jpg"%}{% endif %}" class="img-responsive">
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %} </code>
</pre>

templates/catalog/products.html
{% extends "catalog/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-detail">
         <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "no-image.jpg"%}{% endif %}" class="img-responsive">
         <h1 class="superh1"> {{ product.name }} </h1>
         <div class="price-cart">
             <p style="font-weight: bold"> Цена: {{ product.price }} руб. </p>
             <p> Артикул: {{ product.vendor_code }} </p>
             {% if product.available %}
                <p class="stock-status"> Товар в наличии </p>
             {% else %}
                <p class="stock-status"> Нет в наличии </p>
             {% endif %}
             <form class="form-style" action="{% url "cart:CartAdd" product.id %}" method="post">
                 {{ cart_product_form }}
                 {% csrf_token %}
                 <input type="submit" value="Добавить в корзину">
             </form>
             <div class="product-description"> {{ product.description | linebreaks}}
             </div>
         </div>
    </div>


{% endblock %}